name: Build Blender

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libx11-dev libxxf86vm-dev libxcursor-dev libxi-dev libxrandr-dev libxinerama-dev libglew-dev libfontconfig1-dev

    - name: Clone Blender repository
      run: |
        git clone https://github.com/blender/blender.git
        cd blender
        git submodule update --init --recursive

    - name: Build Blender
      run: |
        cd blender
        mkdir build
        cd build
        cmake ..
        make -j$(nproc)

    - name: Run tests
      run: |
        cd blender/build
        make test
