name: Build Blender

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  build_blender:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt install build-essential git git-lfs subversion cmake libx11-dev libxxf86vm-dev libxcursor-dev libxi-dev libxrandr-dev libxinerama-dev libegl-dev
        sudo apt install libwayland-dev wayland-protocols libxkbcommon-dev libdbus-1-dev linux-libc-dev

    - name: Clone Blender repository and libraries
      run: |
          mkdir ~/blender-git
          cd ~/blender-git
          git clone https://github.com/blender/blender.git
          cd ~/blender-git/blender
          ./build_files/utils/make_update.py --use-linux-libraries
          
    - name: Build Blender
      run: |
        cd ~/blender-git/blender         
        make update
        make -j$(nproc)

    - name: Prepare release
      run: |
        cd ~/blender-git
        tar -cvf blender_build.tar.gz blender/build_linux
      
    - name: Publish to GitHub
      id: release
      uses: softprops/action-gh-release@v2
      with:
        files: ~/blender-git/blender_build.tar.gz
        name: Blender_build_${{ github.run_number }}
        tag_name: ${{ github.run_number }}
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
